// week5_React/src/component/TodoForm.js
import React,{Component} from 'react';

import PropTypes from 'prop-types';

import Button from './Button';

export default class TodoForm extends Component{
	// 声明并验证context
	static contextTypes = {
		handlerAdd:PropTypes.func
	}

	constructor(){
		super();

		this.state = {
			keyword:''
		}


		this.handlerChangeKeyword = this.handlerChangeKeyword.bind(this);
		this.handlerAdd = this.handlerAdd.bind(this);
		this.handlerKeyup = this.handlerKeyup.bind(this);
	}

	handlerChangeKeyword(e){
		this.setState({
			keyword:e.target.value
		});
	}

	handlerAdd(){
		this.context.handlerAdd(this.state.keyword);
		this.state.keyword = '';
		this.refs.keyword.focus();
	}

	// 回车发送消息
	handlerKeyup(e){
		if(e.keyCode === 13){
			this.handlerAdd();
		}
	}
	
	render(){console.log(this)
		return <div className="form">
			<div className="input-group">
				<input type="text" className="form-control" ref="keyword" value={this.state.keyword} onChange={this.handlerChangeKeyword} onKeyUp={this.handlerKeyup}/>
				<div className="input-group-append">
					<Button className="btn btn-success" onClick={this.handlerAdd}>添加</Button>
				</div>
			</div>
		</div>	
	}
}

// week3_Vue/src/components/TodoForm.vue
<template>
    <div class="input-group mb-3">
        <input type="search" ref="form" class="form-control" @keyup.13="add" v-model="text">
        <div class="input-group-append">
            <Button class="btn-success" :handleClick="add">添加</Button>
        </div>
    </div>
</template>

<script>
import Button from './Button.vue';
import bus from '@/js/bus';

// 暴露接口，用于其他模块的引入
export default {
    data(){
        return {
            text:''
        }
    },
    methods:{
        add(){
            // console.log(6666)
            // this.handlerAdd({text:'xxx'})

            // 触发自定义事件：this.$emit(type,data)
            //  * type： 自定义事件名
            //  * data： 传输的数据

            bus.$emit('additem',{
                text:this.text
            });

            // 清空并自动获得焦点
            this.text = '';
            this.$refs.form.focus();
        }
    },

    mounted(){
        // 进入页面，自动获得焦点
        this.$refs.form.focus();
    },

    components:{
        Button
    }
}


// 等效于 export let TodoForm = {}
</script>
